[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[theme]
base = "dark"
primaryColor = "#C9702A"
backgroundColor = "#111417"
secondaryBackgroundColor = "#1a1e23"
textColor = "#ECECEC"
font = "sans serif"
